CREATE TABLE IF NOT EXISTS job_config (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  client_id VARCHAR(250) NOT NULL,
  job_name VARCHAR(250) NOT NULL,
  config_name VARCHAR(250) NOT NULL,
  "value" VARCHAR(250) DEFAULT NOT NULL
);